#Base 
baseURL = 'yukari.online'
languageCode = 'en-us'
title = "Yukari's Blog"
theme = "Mainroad"
[params]
  description = "Yukari's blog" # 网站描述
  author = "Yukari"        # 显示在侧边栏的作者名
  
  # 侧边栏设置 (默认在右边)
  sidebar_position = "right" 
  
  # 侧边栏组件 (你可以根据需要增删)
  widgets = ["search", "recent", "categories", "taglist", "social"]
  
  # 社交链接 (显示在侧边栏 Social 组件)
  [params.social]
    github = "https://github.com/yukari502"
    email = "mailto:你的邮箱"

[menu]
  # 顶部导航菜单
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "archives"
    name = "Archive"
    url = "/post/"
    weight = 20