name: Deploy to GCP

on:
  push:
    branches:
      - master # 或者是 master，看你的默认分支叫什么

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true  # 必须开启，因为主题通常是子模块
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify --baseURL "https://yukari.online/" # 替换为你的域名

      - name: Deploy to Server via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "public/*"      # Hugo 生成的静态文件都在这里
          target: "/var/www/html" # 服务器的目标目录
          strip_components: 1     # 去掉 public 这一层文件夹，直接把内容拷进去